version: '3.5'
services:
  postgresserver:
    image: postgres:alpine
    container_name: budgie_db_server
    hostname: postgres-server
    restart: always
    ports:
      - "4444:5432"
    environment:
      TZ: "Asia/Bangkok"
      POSTGRES_DB: budgie_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGPORT: 5432
      POSTGRES_HOST_AUTH_METHOD: trust
    command:
      -c ssl=off
